name: ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Bulid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Build
        run: go build -v ./...

      name: Run testing
      run: cd test && go test -v
